name: AutoMine
version: '${project.version}'
main: ru.anime.automine.Main
api-version: '1.16'
commands:
  automine:
    aliases:
      - am
permissions:
  automine.admin:
    default: op
  automine.create:
    default: op
  automine.update:
    default: op
  automine.set:
    default: op

depend:
  - PlaceholderAPI
  - DecentHolograms
softdepend:
  - MultiWorld